############# German navigation ##############

# main menu
[[main]]
name = "Startseite"
url = "/"
weight = 1

[[main]]
name = "Über uns"
url = "/about"
weight = 2

[[main]]
name = "Elemente"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Seiten"

[[main]]
parent = "Seiten"
name = "Blog"
url = "/blog"

[[main]]
parent = "Seiten"
name = "Kontakt"
url = "/contact"

[[main]]
parent = "Seiten"
name = "Autoren"
url = "/authors"

[[main]]
parent = "Seiten"
name = "Kategorien"
url = "/categories"

[[main]]
parent = "Seiten"
name = "404 Seite"
url = "/404"


# footer menu
[[footer]]
name = "Über uns"
url = "/about"
weight = 1

[[footer]]
name = "Elemente"
url = "/elements"
weight = 2

[[footer]]
name = "Datenschutzerklärung"
url = "/privacy-policy"
weight = 3
